Simplify manual config-desciption of sealed-traits
zio/zio-config pull request #451
Opened 2020-11-27 03:27 UTC by afsalthaj

Fix #450

2020-11-27 04:56 UTC, afsalthaj commented on core/src/main/scala/zio/config/ConfigDescriptorModule.scala
> +    class PartiallyAppliedEnum[D] {
To avoid users having to give types for all subtypes

2020-11-27 15:46 UTC, jdegoes commented on core/src/main/scala/zio/config/ConfigDescriptorModule.scala
> +    def enum[D] = new PartiallyAppliedEnum[D]
We should call this `enumeration` rather than `enum`, because in Scala 3, `enum` is a keyword.

2020-11-27 15:48 UTC, jdegoes requested changes
Good to merge after `enum` is renamed to `enumeration`. Looks great!

2020-11-27 22:01 UTC, afsalthaj commented
@jdegoes Thanks John.
I have renamed it. I don't have merge permission without an approval

2020-11-28 14:32 UTC, jdegoes approved these changes

2020-11-28 14:50 UTC, merged